### ISSUE TITLE
Compute Gauss-Legendre nodes with O(1) algorithm by I. Bogaert?

### ISSUE THREAD

**Issue by JSorngard** [DomiDre/gauss-quad#14]
I implemented the [Gauss-Legendre algorithm by I. Bogaert](https://epubs.siam.org/doi/10.1137/140954969) and thought about publishing it as my own crate, before I found this one. Would it be a interesting addition?
The stand-out property of that algorithm is that any node weight pair can be computed accurately in O(1) time. It's also easy to parallelize.

My implementation of it is currently at https://github.com/JSorngard/fast_gauleg

If this is of interest I can try doing it, but I don't want to jump in to someone else's project with a pull request without checking that it's a welcome idea first.

**Comment by DomiDre** [comment]
Hey sorry for my late reply... Your idea is very welcome if you want to have your code integrated. I will put it on my list to also look into it otherwise!

**Comment by JSorngard** [comment]
What is your position on API changes?
I can make the `integrate`, `init` and `nodes_and_weights` functions run in parallel (behind a feature flag), and that will be much more efficient if the `GaussLegendre` struct were to store a single vector of node-weight pairs instead of two separate vectors, and if `nodes_and_weights` returns a `Vec<NodeWeightPair>`.
If that is not a desirable change, I'll just implement them with the current API, and parallelism can be implemented later if desired.

**Comment by JSorngard** [comment]
Implemented in PR #15
