### ISSUE TITLE
Add par_integrate for the quadrature rules

### ISSUE THREAD

**Issue by DomiDre** [DomiDre/gauss-quad#47]
As shown in the benchmark discussed in issue #29. There might be a possibility that for complex integrands or very large node numbers the overhead of running the integration in parallel might give a speed up.

Should rayon be included in the crate and par_integrate given for every quadrature rule or is it a distraction for the simple integrals where it is rather a slow down?

**Comment by JSorngard** [comment]
I think it might be a good idea to include it behind a feature gate, so that users of the crate only need to compile it if they want.

**Comment by JSorngard** [comment]
[This Stackoverflow answer](https://stackoverflow.com/questions/61417452/how-to-get-a-feature-requirement-tag-in-the-documentation-generated-by-cargo-do) contains nice information about how to add a little badge to the documentation on docs.rs that shows a function is only available if a certain feature is enabled. That could be nice for when par_integrate is added.
